"""initial_schema

Revision ID: 07a2e33bc505
Revises: 
Create Date: 2026-09-26 15:35:01.344393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '07a2e33bc505'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_types',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('ml_class_names', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_types_code'), 'equipment_types', ['code'], unique=True)
    op.create_table('project_types',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_types_code'), 'project_types', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=127), nullable=False),
    sa.Column('last_name', sa.String(length=127), nullable=False),
    sa.Column('roles', postgresql.ARRAY(sa.String()), server_default=sa.text("ARRAY['user']::text[]"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('type_id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('schedule_status', sa.String(length=32), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('current_alert_level', sa.String(length=16), server_default=sa.text("'GREEN'"), nullable=False),
    sa.Column('current_special_status', sa.String(length=16), server_default=sa.text("'NONE'"), nullable=False),
    sa.Column('yellow_alert_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['type_id'], ['project_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_creator_id'), 'projects', ['creator_id'], unique=False)
    op.create_index(op.f('ix_projects_type_id'), 'projects', ['type_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('stage_templates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('type_id', sa.UUID(), nullable=False),
    sa.Column('stage_name', sa.String(length=255), nullable=False),
    sa.Column('substage_name', sa.String(length=255), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('default_duration_days', sa.Integer(), nullable=False),
    sa.Column('default_equipment', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['project_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_templates_type_id'), 'stage_templates', ['type_id'], unique=False)
    op.create_table('audit_trail',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_trail_action_type'), 'audit_trail', ['action_type'], unique=False)
    op.create_index(op.f('ix_audit_trail_created_at'), 'audit_trail', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_trail_project_id'), 'audit_trail', ['project_id'], unique=False)
    op.create_index(op.f('ix_audit_trail_user_id'), 'audit_trail', ['user_id'], unique=False)
    op.create_table('cameras',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('stream_url', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cameras_project_id'), 'cameras', ['project_id'], unique=False)
    op.create_table('project_assignments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_in_project', sa.String(length=32), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_assignments_project_id'), 'project_assignments', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_assignments_user_id'), 'project_assignments', ['user_id'], unique=False)
    op.create_table('project_schedules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('stage_name', sa.String(length=255), nullable=False),
    sa.Column('substage_name', sa.String(length=255), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('base_start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('base_end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('phantom_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phantom_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'PLANNED'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_schedules_project_id'), 'project_schedules', ['project_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('yellow_to_red_timeout_hours', sa.Integer(), server_default=sa.text('48'), nullable=False),
    sa.Column('idle_threshold_minutes', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.Column('frame_retention_days', sa.Integer(), server_default=sa.text('7'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_project_id'), 'system_settings', ['project_id'], unique=True)
    op.create_table('camera_frame_analyses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('image_path', sa.String(length=1024), nullable=False),
    sa.Column('is_saved_for_report', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('detection_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embeddings_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_frame_analyses_camera_id'), 'camera_frame_analyses', ['camera_id'], unique=False)
    op.create_index(op.f('ix_camera_frame_analyses_captured_at'), 'camera_frame_analyses', ['captured_at'], unique=False)
    op.create_index(op.f('ix_camera_frame_analyses_is_saved_for_report'), 'camera_frame_analyses', ['is_saved_for_report'], unique=False)
    op.create_index(op.f('ix_camera_frame_analyses_processed_at'), 'camera_frame_analyses', ['processed_at'], unique=False)
    op.create_index(op.f('ix_camera_frame_analyses_project_id'), 'camera_frame_analyses', ['project_id'], unique=False)
    op.create_table('camera_interval_analytics',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=True),
    sa.Column('camera_id', sa.UUID(), nullable=True),
    sa.Column('interval_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interval_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active_equipment_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('idle_equipment_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('required_equipment_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('equipment_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('compliance_status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['project_schedules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_interval_analytics_camera_id'), 'camera_interval_analytics', ['camera_id'], unique=False)
    op.create_index(op.f('ix_camera_interval_analytics_interval_start'), 'camera_interval_analytics', ['interval_start'], unique=False)
    op.create_index(op.f('ix_camera_interval_analytics_project_id'), 'camera_interval_analytics', ['project_id'], unique=False)
    op.create_index(op.f('ix_camera_interval_analytics_schedule_id'), 'camera_interval_analytics', ['schedule_id'], unique=False)
    op.create_table('stage_equipment_requirements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('equipment_type', sa.String(length=64), nullable=False),
    sa.Column('required_count', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_type'], ['equipment_types.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['schedule_id'], ['project_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_equipment_requirements_equipment_type'), 'stage_equipment_requirements', ['equipment_type'], unique=False)
    op.create_index(op.f('ix_stage_equipment_requirements_schedule_id'), 'stage_equipment_requirements', ['schedule_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('trigger_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'OPEN'"), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('escalate_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('yellow_escalated_to_red_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger_frame_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['project_schedules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trigger_frame_id'], ['camera_frame_analyses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_escalate_at'), 'alerts', ['escalate_at'], unique=False)
    op.create_index(op.f('ix_alerts_project_id'), 'alerts', ['project_id'], unique=False)
    op.create_index(op.f('ix_alerts_schedule_id'), 'alerts', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_trigger_frame_id'), 'alerts', ['trigger_frame_id'], unique=False)
    op.create_index('uq_open_alert_per_stage_trigger', 'alerts', ['project_id', sa.literal_column("COALESCE(schedule_id, '00000000-0000-0000-0000-000000000000'::uuid)"), 'trigger_type'], unique=True, postgresql_where=sa.text("status = 'OPEN'"))
    op.create_table('alert_resolutions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('engineer_id', sa.UUID(), nullable=False),
    sa.Column('action_taken', sa.String(length=32), nullable=False),
    sa.Column('engineer_comment', sa.Text(), nullable=False),
    sa.Column('evidence_frame_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['engineer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_resolutions_alert_id'), 'alert_resolutions', ['alert_id'], unique=True)
    op.create_table('special_status_windows',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('target_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason_comment', sa.Text(), nullable=False),
    sa.Column('close_comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_special_status_windows_alert_id'), 'special_status_windows', ['alert_id'], unique=False)
    op.create_index(op.f('ix_special_status_windows_project_id'), 'special_status_windows', ['project_id'], unique=False)
    op.create_table('orange_status_reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('special_status_window_id', sa.UUID(), nullable=False),
    sa.Column('is_plan_caught_up', sa.Boolean(), nullable=False),
    sa.Column('time_lost_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('responsible_party', sa.Text(), nullable=True),
    sa.Column('summary_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['special_status_window_id'], ['special_status_windows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orange_status_reports_special_status_window_id'), 'orange_status_reports', ['special_status_window_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orange_status_reports_special_status_window_id'), table_name='orange_status_reports')
    op.drop_table('orange_status_reports')
    op.drop_index(op.f('ix_special_status_windows_project_id'), table_name='special_status_windows')
    op.drop_index(op.f('ix_special_status_windows_alert_id'), table_name='special_status_windows')
    op.drop_table('special_status_windows')
    op.drop_index(op.f('ix_alert_resolutions_alert_id'), table_name='alert_resolutions')
    op.drop_table('alert_resolutions')
    op.drop_index('uq_open_alert_per_stage_trigger', table_name='alerts', postgresql_where=sa.text("status = 'OPEN'"))
    op.drop_index(op.f('ix_alerts_trigger_frame_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_schedule_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_project_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_escalate_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_stage_equipment_requirements_schedule_id'), table_name='stage_equipment_requirements')
    op.drop_index(op.f('ix_stage_equipment_requirements_equipment_type'), table_name='stage_equipment_requirements')
    op.drop_table('stage_equipment_requirements')
    op.drop_index(op.f('ix_camera_interval_analytics_schedule_id'), table_name='camera_interval_analytics')
    op.drop_index(op.f('ix_camera_interval_analytics_project_id'), table_name='camera_interval_analytics')
    op.drop_index(op.f('ix_camera_interval_analytics_interval_start'), table_name='camera_interval_analytics')
    op.drop_index(op.f('ix_camera_interval_analytics_camera_id'), table_name='camera_interval_analytics')
    op.drop_table('camera_interval_analytics')
    op.drop_index(op.f('ix_camera_frame_analyses_project_id'), table_name='camera_frame_analyses')
    op.drop_index(op.f('ix_camera_frame_analyses_processed_at'), table_name='camera_frame_analyses')
    op.drop_index(op.f('ix_camera_frame_analyses_is_saved_for_report'), table_name='camera_frame_analyses')
    op.drop_index(op.f('ix_camera_frame_analyses_captured_at'), table_name='camera_frame_analyses')
    op.drop_index(op.f('ix_camera_frame_analyses_camera_id'), table_name='camera_frame_analyses')
    op.drop_table('camera_frame_analyses')
    op.drop_index(op.f('ix_system_settings_project_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_project_schedules_project_id'), table_name='project_schedules')
    op.drop_table('project_schedules')
    op.drop_index(op.f('ix_project_assignments_user_id'), table_name='project_assignments')
    op.drop_index(op.f('ix_project_assignments_project_id'), table_name='project_assignments')
    op.drop_table('project_assignments')
    op.drop_index(op.f('ix_cameras_project_id'), table_name='cameras')
    op.drop_table('cameras')
    op.drop_index(op.f('ix_audit_trail_user_id'), table_name='audit_trail')
    op.drop_index(op.f('ix_audit_trail_project_id'), table_name='audit_trail')
    op.drop_index(op.f('ix_audit_trail_created_at'), table_name='audit_trail')
    op.drop_index(op.f('ix_audit_trail_action_type'), table_name='audit_trail')
    op.drop_table('audit_trail')
    op.drop_index(op.f('ix_stage_templates_type_id'), table_name='stage_templates')
    op.drop_table('stage_templates')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_projects_type_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_creator_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_project_types_code'), table_name='project_types')
    op.drop_table('project_types')
    op.drop_index(op.f('ix_equipment_types_code'), table_name='equipment_types')
    op.drop_table('equipment_types')
    # ### end Alembic commands ###