"""add_critical_path_and_allowed_equipment

Revision ID: 10e159511290
Revises: 07a2e33bc505
Create Date: 2026-09-27 09:21:55.128871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '10e159511290'
down_revision: Union[str, None] = '07a2e33bc505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_schedules', sa.Column('is_critical_path', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('project_schedules', sa.Column('allowed_equipment', postgresql.ARRAY(sa.String()), server_default=sa.text('ARRAY[]::varchar[]'), nullable=False))
    op.add_column('project_schedules', sa.Column('alerts_and_risks', sa.Text(), nullable=True))
    op.add_column('stage_templates', sa.Column('is_critical_path', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('stage_templates', sa.Column('allowed_equipment', postgresql.ARRAY(sa.String()), server_default=sa.text('ARRAY[]::varchar[]'), nullable=False))
    op.add_column('stage_templates', sa.Column('alerts_and_risks', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stage_templates', 'alerts_and_risks')
    op.drop_column('stage_templates', 'allowed_equipment')
    op.drop_column('stage_templates', 'is_critical_path')
    op.drop_column('project_schedules', 'alerts_and_risks')
    op.drop_column('project_schedules', 'allowed_equipment')
    op.drop_column('project_schedules', 'is_critical_path')
    # ### end Alembic commands ###