"""initial_schema

Revision ID: cbfea419eb66
Revises: 
Create Date: 2026-09-26 15:27:49.332871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'cbfea419eb66'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('escalate_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('alerts', sa.Column('trigger_frame_id', sa.UUID(), nullable=True))
    op.add_column('alerts', sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_alerts_escalate_at'), 'alerts', ['escalate_at'], unique=False)
    op.create_index(op.f('ix_alerts_trigger_frame_id'), 'alerts', ['trigger_frame_id'], unique=False)
    op.create_index('uq_open_alert_per_stage_trigger', 'alerts', ['project_id', sa.literal_column("COALESCE(schedule_id, '00000000-0000-0000-0000-000000000000'::uuid)"), 'trigger_type'], unique=True, postgresql_where=sa.text("status = 'OPEN'"))
    op.create_foreign_key(None, 'alerts', 'camera_frame_analyses', ['trigger_frame_id'], ['id'], ondelete='SET NULL')
    op.add_column('camera_interval_analytics', sa.Column('active_equipment_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('camera_interval_analytics', sa.Column('idle_equipment_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('camera_interval_analytics', sa.Column('required_equipment_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('special_status_windows', sa.Column('close_comment', sa.Text(), nullable=True))
    op.alter_column('stage_equipment_requirements', 'equipment_type',
               existing_type=sa.VARCHAR(length=127),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.create_foreign_key(None, 'stage_equipment_requirements', 'equipment_types', ['equipment_type'], ['code'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'stage_equipment_requirements', type_='foreignkey')
    op.alter_column('stage_equipment_requirements', 'equipment_type',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=127),
               existing_nullable=False)
    op.drop_column('special_status_windows', 'close_comment')
    op.drop_column('camera_interval_analytics', 'required_equipment_count')
    op.drop_column('camera_interval_analytics', 'idle_equipment_count')
    op.drop_column('camera_interval_analytics', 'active_equipment_count')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_index('uq_open_alert_per_stage_trigger', table_name='alerts', postgresql_where=sa.text("status = 'OPEN'"))
    op.drop_index(op.f('ix_alerts_trigger_frame_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_escalate_at'), table_name='alerts')
    op.drop_column('alerts', 'details')
    op.drop_column('alerts', 'trigger_frame_id')
    op.drop_column('alerts', 'escalate_at')
    # ### end Alembic commands ###